##############################################################################
#              PROXYPASS TO S3 OLAP
##############################################################################

SSLProxyEngine On
ProxyPassInterpolateEnv On
ProxyRequests off

# ErrorLog "logs/warren_test_error_log"
LogLevel error proxy:trace6
# SetEnvIf Request_URI "^(.*)/admissions/files/(.*)$" warren_test
# # SetEnvIf Request_URI (.*) warren_test
# LogFormat "%h %l %u %t \"%r\" %>s %b %D microseconds" warren_test_log
# CustomLog "logs/warren_test_log" warren_test_log env=warren_test

SetEnvIf ^Eppn$ .+ warren_test
CustomLog logs/warren_test_log combined env=warren_test
SetEnvIf ^eppn$ .+ warren_test2
CustomLog logs/warren_test2_log combined env=warren_test2
SetEnvIf ^Host$ .+ warren_test3
CustomLog logs/warren_test3_log combined env=warren_test3


# Unset headers: you must unset X-Amz-Cf-Id, else InvalidSignature error will result. X-Amzn-Trace-Id seems innocuous, but is unnecessary.
RequestHeader unset X-Amz-Cf-Id
RequestHeader unset X-Amzn-Trace-Id

RewriteRule ^/+([a-zA-Z0-9_\-]+/)?files/(.*)$ http://localhost:8080/$1files/$2 [P]

# RewriteRule ^/+([a-zA-Z0-9_\-]+/)?files/(.*)$ - [E=proxy_pass_host:internal-s3pro-s3pro-1KSB20ENDT9VW-1289646701.us-east-1.elb.amazonaws.com,P]
# RewriteRule ^/+([a-zA-Z0-9_\-]+/)?files/(.*)$ - [E=proxy_pass_host:s3proxy.kualitest.research.bu.edu,P]
# ProxyPass / "https://${proxy_pass_host}/" interpolate
# ProxyPassReverse / "https://${proxy_pass_host}/" interpolate

# Define custom error pages for proxy errors
ProxyErrorOverride On

ErrorDocument 401 /_s3proxy-custom-errors/401-unauthorized.php
ErrorDocument 403 /_s3proxy-custom-errors/403-forbidden.php
ErrorDocument 404 /_s3proxy-custom-errors/404-not-found.php
