RewriteEngine on
RewriteRule ^/?robots.txt /var/www/robots.txt [L,NC]

# 3:16 PM 1/9/2024 - Warren: Commented out this line because it has a syntax error and httpd cannot be reloaded/restarted.
# RewriteCond .git -f %{DOCUMENT_ROOT}/.git

#RewriteCond expr "! -R '192.168.1.0/24'"
RewriteRule (.*) offline.html [L]
