#
# The following lines prevent .user.ini files from being viewed by Web clients.
#
<Files ".user.ini">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order allow,deny
        Deny from all
        Satisfy All
    </IfModule>
</Files>

#
# Allow php to handle Multiviews
#
AddType text/html .php

#
# Add index.php to the list of files that will be served as directory
# indexes.
#
DirectoryIndex index.php

# mod_php options
<IfModule  mod_php7.c>
    #
    # Cause the PHP interpreter to handle files with a .php extension.
    #
    <FilesMatch \.(php|phar)$>
        SetHandler application/x-httpd-php
    </FilesMatch>

    #
    # Uncomment the following lines to allow PHP to pretty-print .phps
    # files as PHP source code:
    #
    #<FilesMatch \.phps$>
    #    SetHandler application/x-httpd-php-source
    #</FilesMatch>

    #
    # Apache specific PHP configuration options
    # those can be override in each configured vhost
    #
    php_value session.save_handler "files"
    php_value session.save_path    "/var/lib/php/session"
    php_value soap.wsdl_cache_dir  "/var/lib/php/wsdlcache"

    # PHP OPcache Configuration (PHP 7.4.33)
    php_admin_value opcache.enable 1
    php_admin_value opcache.enable_cli 1
    php_admin_value opcache.memory_consumption 512
    php_admin_value opcache.max_accelerated_files 100000
    php_admin_value opcache.validate_timestamps 1
    php_admin_value opcache.revalidate_freq 2
    php_admin_value opcache.revalidate_path 0
    php_admin_value opcache.file_update_protection 2
    php_admin_value opcache.interned_strings_buffer 16
    php_admin_value opcache.save_comments 1
    php_admin_value opcache.enable_file_override 1
    php_admin_value opcache.file_cache_only 0
    php_admin_value opcache.huge_code_pages 0
</IfModule>
