##############################################################################
#              PROXYPASS TO S3 OLAP
##############################################################################

SSLProxyEngine On
ProxyPassInterpolateEnv On
ProxyRequests off

# Unset headers: you must unset X-Amz-Cf-Id, else InvalidSignature error will result. X-Amzn-Trace-Id seems innocuous, but is unnecessary.
RequestHeader unset X-Amz-Cf-Id
RequestHeader unset X-Amzn-Trace-Id

RewriteRule ^/+([a-zA-Z0-9_\-]+/)?files/(.*)$ http://localhost:8080/$1files/$2 [P]

# RewriteRule ^/+([a-zA-Z0-9_\-]+/)?files/(.*)$ - [E=proxy_pass_host:internal-s3pro-s3pro-1KSB20ENDT9VW-1289646701.us-east-1.elb.amazonaws.com,P]
# RewriteRule ^/+([a-zA-Z0-9_\-]+/)?files/(.*)$ - [E=proxy_pass_host:s3proxy.kualitest.research.bu.edu,P]
# ProxyPass / "https://${proxy_pass_host}/" interpolate
# ProxyPassReverse / "https://${proxy_pass_host}/" interpolate

# Define custom error pages for proxy errors (testing)
ProxyErrorOverride On

ErrorDocument 401 /_s3proxy-custom-errors/401-unauthorized.php
ErrorDocument 403 /_s3proxy-custom-errors/403-forbidden.php
ErrorDocument 404 /_s3proxy-custom-errors/404-not-found.php
